### PR TITLE
Use Attribute.$observe for 'parameter' and 'collect' attributes

### PR DESCRIPTION
**Pull request by paracycle**
In order to allow for interpolated values

### CODE REVIEW

**Comment by atesgoral** [comment]
👍

**Comment by atesgoral** [comment]
Do we know if this will be 100% backwards compatible? Also, do you think this should be a patch version or a minor version bump?

**Comment by unframework** [comment]
Per @paracycle this would not work in 1.0, but upwards is fine.

**Comment by unframework** [comment]
Might be better as minor version bump.

**Comment by paracycle** [comment]
Thanks gents...

**Pull request merged**
